manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk_caksoylar
      remote: caksoylar
      revision: a55f26daef34c58ddc4cb997d2f8450b30f413df
      import: app/west.yml
    - name: zmk_urob
      remote: urob
      revision: main
      import: app/west.yml
  self:
    path: config
